### ISSUE TITLE
Cannot import Update from telegram

### ISSUE THREAD

**Issue by shlokthakkar2** [neerajkumarc/telegram-quote-bot#1]
ImportError: cannot import name 'Update' from 'telegram'

**Comment by neerajkumarc** [comment]
Install all the packages by running following command:
pip install -r .\requirements.txt

**Comment by shlokthakkar2** [comment]
Thankyou for that ! however another issue I am facing is of invalid token .I got an API key from botfather but it still shows that issue.

**Comment by neerajkumarc** [comment]
if you are using an .env file make sure it is in following format :
TOKEN=6316321218:XXXXXbM99XoX8-vkXHetTwddIJs5C6XXXX8

**Comment by shlokthakkar2** [comment]
No I am not using an env file , I have directly put in the api in the code like this : 

`TOKEN = os.getenv('xxxxxxxxxx:BBATi9KJoIio6GWlA-HlNTGML95IKpQTnWp')`

**Comment by neerajkumarc** [comment]
if you are not using .env file then don't use os.getenv() method instead re-write the following line like this:
TOKEN = "6316321218:XXXXXbM99XoX8-vkXHetTwddIJs5C6XXXX8"

**Comment by shlokthakkar2** [comment]
yeah I did that. my bad I did not realise
